services:
  server:
    container_name: code-sync-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  client:
    container_name: code-sync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:3000}
    ports:
      - "80:80"
    depends_on:
      - server
